# 公共配置
spring:
  profiles:
    # 激活哪一个环境的配置文件
    active: dev

---
# 开发环境
spring:
  profiles: dev
  servlet:
    multipart:
      # 单个文件上传大小限制, 单位为KB, MB
      max-file-size: 1000MB
      # 多个文件上传总大小限制
      max-request-size: 3000MB
  lucene:
    # Lucene索引根路径
    root-path: "E:/lucene/"
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 5000
    # Redis缓存时间, 单位: 秒
    default-cache-time: 100
    short-cache-time: 300
    long-cache-time: 1800
    lucene-cache-time: 60
    pool:
      # 最大空闲连接数(默认为8, 负数表示无限)
      max-idle: 8
      # 最小空闲连接数(默认为0, 该值只有为正数才有作用)
      min-idle: 0
      # 连接池最大连接数(使用负值表示没有限制)
      max-active: 8
      # 连接池最大阻塞等待时间(使用负值表示没有限制)
      max-wait: -1

---
# 生产环境
spring:
  profiles: pro